site: olafur.org
title: Ólafur Nielsen - Developer by ♥ Catalyst by profession
greetings: Hello! 👋🏻
description: >-
  <strong>I'm Olafur (Oli) Nielsen</strong><br />
  Developer by ❤️‍🔥<br />
  <abbr data-title="A person that causes or speeds an important change.">Catalyst</abbr> by profession, usually found at the intersection of emerging technologies and business. 
  
lang: en-US
timezone:  Atlantic/Reykjavik
repo: https://github.com/olafurnielsen/olafurnielsen.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: olafurnielsen
  bio: just a minimalist, personal blog
  userpicture: 
  username: olafurnielsen # general username
  github: olafurnielsen # github username
  twitter: olafurnielsen # twitter username
  email: on@olafur.org # email adress

# URL settings
url: "https://olafur.org" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


